spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://user:AVNS_9hhNls5JtmcGFCqe8mX@vish-db-do-user-13230063-0.b.db.ondigitalocean.com:25060/vish-dev?ssl-mode=REQUIRED
    driver-class-name: com.mysql.cj.jdbc.Driver

