server:
  port: 8080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://user:AVNS_9hhNls5JtmcGFCqe8mX@vish-db-do-user-13230063-0.b.db.ondigitalocean.com:25060/vish-dev?ssl-mode=REQUIRED
    driver-class-name: com.mysql.cj.jdbc.Driver
